[tool.poetry]
name = "hw6"
version = "0.1.0"
description = ""
authors = ["Joohny21 <112joohny@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiopath = "^0.6.11"
aioshutil = "^1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
